# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CatcraftTimes!
email: by pillow and Evie
description: > # this means to ignore newlines until "baseurl:"
  Creating FFXIV mods :> All content 
  in shop or sub is custom created by us!
  Join our discord, i will be happy! <3
baseurl: "/web" # the subpath of your site, e.g. /blog
url: "https://catcraftxiv.github.io/web/" # the base hostname & protocol for your site
github_username:    
instagram_username: 
twitter_username:   catcraftxiv
patreon_username:   catcraftffxiv
xma_username:       
tgd_username:     
discord_username:   yPbUXazxQ3  

# List of profiles
xma_profile: https://www.xivmodarchive.com/user/111283
tgd_profile: https://www.glamourdresser.com/author/catcraft
patreon_profile: https://www.patreon.com/catcraftFFXIV
patreon.shop_profile: https://www.patreon.com/catcraftffxiv/shop
pillow.boosty_profile: https://boosty.to/miaumori
evie.boosty_profile: https://boosty.to/evilieda
hipolink_profile: https://hipolink.me/pomigrein
hipolink.shop_profile: https://hipolink.me/pomigrein/products
kofi_profile: https://ko-fi.com/catcraft
website_profile: https://catcraftxiv.github.io/web/
discord_profile: https://discord.gg/yPbUXazxQ3
twitter_profile: https://x.com/catcraftxiv
bsky_profile: https://bsky.app/profile/catcraftxiv.bsky.social
mod.rules_profile: https://catcraftxiv.github.io/web/rules


# Build settings
markdown: kramdown
