# List of profiles
- name: XMA
  link: https://www.xivmodarchive.com/user/111283
  frontpage: true

- name: TGD
  link: https://www.glamourdresser.com/author/catcraft
  frontpage: true
  
xma_profile: https://www.xivmodarchive.com/user/111283
tgd_profile: https://www.glamourdresser.com/author/catcraft
patreon_profile: https://www.patreon.com/catcraftFFXIV
patreon.shop_profile: https://www.patreon.com/catcraftffxiv/shop
pillow.boosty_profile: https://boosty.to/miaumori
evie.boosty_profile: https://boosty.to/evilieda
hipolink_profile: https://hipolink.me/pomigrein
hipolink.shop_profile: https://hipolink.me/pomigrein/products
kofi_profile: https://ko-fi.com/catcraft
website_profile: https://catcraftxiv.github.io/web/
discord_profile: https://discord.gg/yPbUXazxQ3
twitter_profile: https://x.com/catcraftxiv
bsky_profile: https://bsky.app/profile/catcraftxiv.bsky.social
mod.rules_profile: https://catcraftxiv.github.io/web/rules
